
from __future__ import annotations
from typing import Protocol, Any, Optional

class TableAdapter(Protocol):
    format: str
    def to_arrow(self) -> Any: ...
    def to_polars(self) -> Any: ...
    def write(self, df: Any, mode: str = "append") -> None: ...
    def delete(self, where: Optional[str] = None) -> None: ...
