class ParquetAdapter:
    def __init__(self, storage_location: str):
        self.storage_location = storage_location
        self.format = 'PARQUET'
    def to_arrow(self): ...
    def to_polars(self): ...
    def write(self, df, mode: str = 'append'): ...
    def delete(self, where=None): ...
