class IcebergAdapter:
    def __init__(self, full_name: str):
        self.full_name = full_name
        self.format = 'ICEBERG'
    def to_arrow(self): ...
    def to_polars(self): ...
    def write(self, df, mode: str = 'append'): ...
    def delete(self, where=None): ...
